### ISSUE TITLE
checksums of UNIX and Windows packages cannot be found

### ISSUE THREAD

**Issue by aremai** [ossec/ossec.github.io#1]
If I want to check the checksums for the UNIX tar.gz and for the Windows binary I get the following message:

The requested path was not found.

so it points to a non-existant file.
Paths to be looked at:
https://bintray.com/artifact/download/ossec/ossec-hids/ossec-hids-2.8.3.tar.gz.sha256
https://bintray.com/artifact/download/ossec/ossec-hids/ossec-agent-win32-2.8.3.exe.sha256

this has probably to do with the moving to the new, revamped website.

please fix it.

**Comment by ddpbsd** [comment]
I haven't had a chance to contact support to find out what's going wrong. In the mean time (and possibly from here on out), I've added the checksums on the site: https://ossec.github.io/docs/whatsnew/checksums/2.8.3/index.html
They're also available in the ossec-docs github repo: https://github.com/ossec/ossec-docs/tree/master/docs/whatsnew/checksums/2.8.3

**Comment by aremai** [comment]
awesome, dan!
it seems to work now, thanks for fixing it :+1:

**Comment by ddpbsd** [comment]
Vic Hargrave did the work. I had it all ready to go and forgot to submit a
pull request...

**Comment by vichargrave** [comment]
I updated the links on ossec.github.io.

**Comment by aremai** [comment]
Hi Vic,

sorry, to reopen this again. I have found another dead-link.
On the page of last year's OSSEC con, you posted the slides of people who talked about OSSEC.
This page with the slides is now gone.
http://www.ossec.net/?page_id=1146

Would it be a big problem if you could re-upload them? I would like to use one of the graphics in Santi's slide for my thesis. But for that his slides need to be publicly available somewhere otherwise I wouldn't be able to use them.

You would do me a big favor!

thanks,
theresa

**Comment by vichargrave** [comment]
Sure I'll post them later today.

-- vic

**Comment by ddpbsd** [comment]
@vichargrave If you need help with the sphinx code to link those/offer them for download, let me know or take a look at the checksum pages.

**Comment by aremai** [comment]
that would be very cool! thanks to the both of you!

**Comment by vichargrave** [comment]
Hi theresa.  I'm working out there to put the slides on the new site.  In
the meantime, send me an email and I'll reply with the slides enclosed.

**Comment by aremai** [comment]
hi vic!
i have the slides already (took them from the old site) but I would need a (public) URL that I can put/mention in my thesis. :)

**Comment by vichargrave** [comment]
Ok got it.  I'm coordinating with Dan on this.  Look for it over the weekend.

**Comment by vichargrave** [comment]
We are talking about the Malware Detection with OSSEC slides, correct?

**Comment by aremai** [comment]
sweet, thanks Vic!
hmm, no sorry...the one from 2013 .. OSSEC_and_OSSIM_Unified_Open_Source_Security.pdf
it has a very nice overview of all OSSEC processes that I'd like to use.

merry christmas! :)

**Comment by vichargrave** [comment]
Ok, I know we have that one, but I'll just restore all of them.

-- Vic

**Comment by vichargrave** [comment]
I tried putting the slides on Bintray, but they have not shown up yet.  Although the team has puts our packets on Bintray, I confess I’m underwhelmed with this service.  Right now I’m trying to put all our presentation on Slideshare, but now that Slideshare is part of LinkedIn, I’m not sure how to create an account for the OSSEC Project.  Bear with me while I figure this out.

— vic

**Comment by vichargrave** [comment]
Ok Theresa, I put the presentations on Bintray and you can get the links
from the new OSSEC website Downloads page -
http://ossec.github.io/downloads.html#presentation-slides.  Find the
presentation you are interested in, right click on it then select Copy Link
or Copy Link Address (depending on which browser you use). You should be
all set.

Let me know whether or not this works for you.

**Comment by aremai** [comment]
awesome, Vic thank you so very much! I know how painful this was, so I really appreciate it :+1: 
you have no idea how much you helped me.

closing this issue now.
